{
  parserClass="ch.imt.sdk.language.parser.SimpleParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="ch.imt.sdk.language.psi"
  psiImplPackage="ch.imt.sdk.language.psi.impl"

  elementTypeHolderClass="ch.imt.sdk.language.psi.SimpleTypes"
  elementTypeClass="ch.imt.sdk.language.psi.SimpleElementType"
  tokenTypeClass="ch.imt.sdk.language.psi.SimpleTokenType"

  psiImplUtilClass="ch.imt.sdk.language.psi.impl.SimplePsiImplUtil"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY {
  mixin="ch.imt.sdk.language.psi.impl.SimpleNamedElementImpl"
  implements="ch.imt.sdk.language.psi.SimpleNamedElement"
  methods=[getKey getValue getName setName getNameIdentifier]
}